format_version: 3
pipelines:
  support-infra:
    group: shared-components
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        includes:
          - 'utils/*'
          - 'redactor/**/*'
          - 'test/**/*'
          - CHANGELOG.md
    stages:
      - build-utils:
          clean_workspace: true
          artifacts:
            - build:
                source: utils/redactor
                destination: utils
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks test
      - check-release:
          clean_workspace: true
          approval: manual
          jobs:
            code:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish-utils:
          clean_workspace: true
          jobs:
            code:
              tasks:
                - fetch:
                    stage: build-utils
                    job: build-utils
                    is_file: yes
                    source: utils/redactor
                    destination: utils
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
  aws-helpers:
    group: repo-history
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test:
          approval: manual
          tasks:
            - exec:
                command: echo
                arguments:
                  - "deprecated pipeline for history only - go see support-infra pipeline"
      - release:
          jobs:
            code:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "deprecated pipeline for history only - go see support-infra pipeline"
      - publish:
          jobs:
            code:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "deprecated pipeline for history only - go see support-infra pipeline"
