format_version: 3
pipelines:
  aws-helpers:
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        includes:
          - utils/aws-helpers
          - 'test/**/*.*'
          - CHANGELOG.md
    stages:
      - test:
          artifacts:
            - build:
                source: utils/redactor
                destination: utils
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks test
      - release:
          clean_workspace: true
          approval: manual
          jobs:
            code:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            code:
              tasks:
                - fetch:
                    stage: test
                    is_file: yes
                    source: utils/redactor
                    destination: utils
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
