#!/bin/bash

set -Eeo pipefail

AWS_DEFAULT_REGION="eu-west-2"

function create_build_trace_id {
  if [ -z $GO_PIPELINE_NAME ]; then
    export BUILD_TRACE_ID=local
  else
    git_hash=$(echo $GO_REVISION_GIT | cut -c 1-8)
    candidate_build_trace_id="$GO_PIPELINE_NAME@$GO_PIPELINE_COUNTER@$GO_STAGE_NAME@$GO_STAGE_COUNTER@$GO_JOB_NAME@$git_hash"
    length_to=${#candidate_build_trace_id}
    length_from=$((length_to-64))

    export BUILD_TRACE_ID=$(echo "$candidate_build_trace_id" | cut -c "$length_from"-"$length_to")
  fi
}

function _get_aws_ssm_secret {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function _assume-ci-agent-role {
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN

  environment=$1
  aws_account_arn=$(aws sts get-caller-identity | jq -r .Arn)
  create_build_trace_id

  if [[ $aws_account_arn =~ "gocd_agent-prod" && $environment = "dev" ]]; then
    echo "Assuming ci-agent-role in dev account"

    desired_account_id=$(_get_aws_ssm_secret "/repo/${environment}/user-input/external/aws-account-id")
    desired_role_arn="arn:aws:iam::$desired_account_id:role/repository-ci-agent"
    json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$BUILD_TRACE_ID")"

    export AWS_ACCESS_KEY_ID="$(echo "$json" | jq -r .Credentials.AccessKeyId)"
    export AWS_SECRET_ACCESS_KEY="$(echo "$json" | jq -r .Credentials.SecretAccessKey)"
    export AWS_SESSION_TOKEN="$(echo "$json" | jq -r .Credentials.SessionToken)"
  else
    echo "Incorrect identity or environment"
  fi
}

function _docker_login {
  echo Logging in to Amazon ECR...
  eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
}

function _promote-docker-image {
  environment_from=$1
  environment_to=$2
  image repo name + image_tag=$3 // image_full_repo_name ???
  # login with AWS
  # login with ECR
  # pull the image
  # login with AWS to the next account
  # login with ECR to the next account
  # push the image
}

set +e