#!/bin/bash

AWS_DEFAULT_REGION="eu-west-2"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
DOJO_IMAGE_VERSION="nhsdev/deductions-infra-dojo:a3ce7038c095298273348419769e327039009bf5"
RELEASER_VERSION="2.1.0"
RELEASER_FILE="utils/releaser-${RELEASER_VERSION}"

mkdir -p utils
if [[ ! -f $RELEASER_FILE ]];then
  wget --quiet -O $RELEASER_FILE https://github.com/kudulab/releaser/releases/download/${RELEASER_VERSION}/releaser
fi
source $RELEASER_FILE
AWS_HELPERS_VERSION=$(releaser::get_last_git_tagged_version)

function get_latest_commit_hash {
  export COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
}

function create_build_trace_id {
  if [ -z $GO_PIPELINE_NAME ]; then
    export BUILD_TRACE_ID=local
  else
    git_hash=$(echo $GO_REVISION_GIT | cut -c 1-8)
    candidate_build_trace_id="$GO_PIPELINE_NAME@$GO_PIPELINE_COUNTER@$GO_STAGE_NAME@$GO_STAGE_COUNTER@$GO_JOB_NAME@$git_hash"

    export BUILD_TRACE_ID=$(echo "$candidate_build_trace_id" | awk '{ print substr( $0, length($0) - 62, length($0) ) }' | sed "s/^[-]*//")
  fi
}

function get_aws_ssm_secret {
  echo "Last tagged version of aws-helpers: ${AWS_HELPERS_VERSION}"
  secret_id=$1
  json=$(dojo -image "$DOJO_IMAGE_VERSION" "aws ssm get-parameter --with-decryption --region eu-west-2 --name $secret_id")
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function _get_aws_ssm_secret {
  echo "Last tagged version of aws-helpers: ${AWS_HELPERS_VERSION}"
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function docker_login {
  >&2 echo Logging in to Amazon ECR...
  eval $(dojo -image "$DOJO_IMAGE_VERSION" "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

function _get_aws_account_id {
    aws sts get-caller-identity | jq -r .Account
}

function get_aws_account_id {
    AWS_ACCOUNT_ID=$(dojo -image "$DOJO_IMAGE_VERSION" "aws sts get-caller-identity | jq -r .Account")
}

function configure_docker_repository_uri {
  docker_login
  get_aws_account_id
  export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
}

function configure_docker_registry_uri {
  docker_login
  get_aws_account_id
  export REGISTRY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
}

function assume_environment_role {
  echo "Last tagged version of aws-helpers: ${AWS_HELPERS_VERSION}"
  CURRENT_DIR=$(pwd)
  cd "$SCRIPT_DIR"
  eval $(dojo -image "$DOJO_IMAGE_VERSION" "./aws-helpers assume_environment_role $1")
  cd "$CURRENT_DIR"
}

function _clear_aws_env_credentials {
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN
  unset AWS_SECURITY_TOKEN
}

function _assume_environment_role {
  # Agent always needs to assume repository-ci-agent role in one of the destination accounts
  # People always need to assume RepoAdmin role in one of the destination accounts
  # The starting role for the agent is gocd_agent-prod in the CI account
  # The starting role for people is NHSDAdminRole in the CI account
  echo "Last tagged version of aws-helpers: ${AWS_HELPERS_VERSION}"
  environment=$1
  aws_account_arn=$(aws sts get-caller-identity | jq -r .Arn)
  create_build_trace_id

  if [[ $aws_account_arn =~ "gocd_agent-prod" || $aws_account_arn =~ "repository-ci-agent" ]]; then
    _clear_aws_env_credentials
    if [[ $environment = "test" ]]; then
      >&2 echo "Assuming CI agent's role in ci account to provision test environment"
      desired_account_id=$(_get_aws_account_id)
    else
      >&2 echo "Assuming CI agent's role in ${environment} account"
      desired_account_id=$(_get_aws_ssm_secret "/repo/${environment}/user-input/external/aws-account-id")
    fi
    desired_role_arn="arn:aws:iam::$desired_account_id:role/repository-ci-agent"
    >&2 echo "Build trace ID will be set as STS session name: $BUILD_TRACE_ID"
    json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$BUILD_TRACE_ID")"

  elif [[ $aws_account_arn =~ "NHSDAdminRole" || $aws_account_arn =~ "RepoAdmin" ]]; then
    if [[ $environment = "test" ]]; then
      >&2 echo "Assuming RepoAdmin's role in ci account to provision test environment"
      desired_account_id=$(_get_aws_account_id)
    else
      echo >&2 "Assuming RepoAdmin's role in ${environment} account"
      desired_account_id=$(_get_aws_ssm_secret "/repo/${environment}/user-input/external/aws-account-id")
    fi
    desired_role_arn="arn:aws:iam::$desired_account_id:role/RepoAdmin"

    >&2 echo "Build trace ID will be set as STS session name: $BUILD_TRACE_ID"
    json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$BUILD_TRACE_ID")"

  elif [[ $aws_account_arn =~ "user" ]]; then
    # This is a human user who didn't assume admin role yet
    >&2 echo "You must assume NHSDAdminRole in the ci account first"
    exit 5
  fi

  if [[ ! -z $json ]]; then
    export AWS_ACCESS_KEY_ID="$(echo "$json" | jq -r .Credentials.AccessKeyId)"
    export AWS_SECRET_ACCESS_KEY="$(echo "$json" | jq -r .Credentials.SecretAccessKey)"
    export AWS_SESSION_TOKEN="$(echo "$json" | jq -r .Credentials.SessionToken)"
    export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
  fi
}

function promote_docker_image {
  # e.g. deductions/ehr-repo:1ab321
  SRC_IMAGE_NAME_AND_TAG=$1
  ENVIRONMENT=$2
  if [ -z "$SRC_IMAGE_NAME_AND_TAG" ]; then
    >&2 echo "Image name and tag must be specified. e.g. deductions/ehr-repo:1ab321"
    exit 5;
  fi
  if [ -z "$ENVIRONMENT" ]; then
    >&2 echo "Environment must be specified. e.g. dev"
    exit 5;
  fi
  declare -A from_environment_promotion_map=(["dev"]="ci" ["test"]="dev" ["pre-prod"]="ci")
  declare -A to_environment_promotion_map=(["dev"]="dev" ["test"]="ci" ["pre-prod"]="pre-prod")

  environment_from=${from_environment_promotion_map[$ENVIRONMENT]}
  environment_to=${to_environment_promotion_map[$ENVIRONMENT]}

  echo >&2 "Promoting docker image from $environment_from to $environment_to..."

  assume_environment_role "$environment_from"
  configure_docker_registry_uri
  IMAGE_FULL_URL="$REGISTRY_URI/$SRC_IMAGE_NAME_AND_TAG"
  echo "Pulling the image from $IMAGE_FULL_URL"
  docker pull "$IMAGE_FULL_URL"
  docker tag "$IMAGE_FULL_URL" "$SRC_IMAGE_NAME_AND_TAG"

  assume_environment_role "$environment_to"
  configure_docker_registry_uri
  IMAGE_FULL_URL="$REGISTRY_URI/$SRC_IMAGE_NAME_AND_TAG"
  docker tag "$SRC_IMAGE_NAME_AND_TAG" "$IMAGE_FULL_URL"
  echo "Pushing the image to $IMAGE_FULL_URL"
  docker push "$IMAGE_FULL_URL"
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  assume_environment_role)
    _assume_environment_role $2
    echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
    echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
    echo "export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN"
  ;;
esac
